package com.ec.dto;

import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.Set;

import com.ec.util.Constant;
import com.ec.util.Util;

public class Order {
    // field generated by DB
    private long orderID;

    // fields from the screen
    private long phoneNo;
    private String email;
    private String firstName;
    private String lastName;
    private String specialComments;
    private String address;
    private String pickUpTime;
    private String pickUpDate;
    private String orderDisplay;

    // fields from the device
    private Set<Category> items;
    private float amount;

    // fields from the application
    private String status;
    private long customerID;
    private String orderDate;
    private Date lastUpdated;
    private String updatedBy;
    private long deviceID;
    private String updatedDateStr;

    public long getOrderID() {
	return orderID;
    }

    public void setOrderID(long orderID) {
	this.orderID = orderID;
    }

    public long getPhoneNo() {
	return phoneNo;
    }

    public void setPhoneNo(long phoneNo) {
	this.phoneNo = phoneNo;
    }

    public String getEmail() {
	return email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    public String getStatus() {
	return status;
    }

    public void setStatus(String status) {
	this.status = status;
    }

    public Set<Category> getItems() {
	return items;
    }

    public void setItems(Set<Category> items) {
	this.items = items;
    }

    public float getAmount() {
	return amount;
    }

    public void setAmount(float amount) {
	this.amount = amount;
    }

    public long getCustomerID() {
	return customerID;
    }

    public void setCustomerID(long customerID) {
	this.customerID = customerID;
    }

    public String getOrderDate() {
	return orderDate;
    }

    public void setOrderDate(String orderDate) {
	this.orderDate = orderDate;
    }

    public Date getLastUpdated() {
	return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
	this.lastUpdated = lastUpdated;
    }

    public String getUpdatedBy() {
	return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public String getFirstName() {
	return firstName;
    }

    public void setFirstName(String firstName) {
	this.firstName = firstName;
    }

    public String getLastName() {
	return lastName;
    }

    public void setLastName(String lastName) {
	this.lastName = lastName;
    }

    public long getDeviceID() {
	return deviceID;
    }

    public void setDeviceID(long deviceID) {
	this.deviceID = deviceID;
    }

    public String getSpecialComments() {
	return specialComments;
    }

    public void setSpecialComments(String specialComments) {
	this.specialComments = specialComments;
    }

    public String getAddress() {
	return address;
    }

    public void setAddress(String address) {
	this.address = address;
    }

    public String getPickUpTime() {
	return pickUpTime;
    }

    public void setPickUpTime(String pickUpTime) {
	this.pickUpTime = pickUpTime;
    }

    public String getPickUpDate() {
	return pickUpDate;
    }

    public void setPickUpDate(String pickUpDate) {
	this.pickUpDate = pickUpDate;
    }

    public String getUpdatedDateStr() {
	if (lastUpdated != null) {
	    updatedDateStr = Util.formatDate(lastUpdated, Constant.DB_DATE_FORMAT);
	}

	return updatedDateStr;
    }

    public void setUpdatedDateStr(String updatedDateStr) {
	this.updatedDateStr = updatedDateStr;
    }

    @Override
    public String toString() {
	final int maxLen = 10;
	return "Order [orderID=" + orderID + ", phoneNo=" + phoneNo + ", email=" + email + ", firstName=" + firstName
		+ ", lastName=" + lastName + ", specialComments=" + specialComments + ", address=" + address + ", pickUpTime="
		+ pickUpTime + ", pickUpDate=" + pickUpDate + ", items=" + (items != null ? toString(items, maxLen) : null)
		+ ", amount=" + amount + ", status=" + status + ", customerID=" + customerID + ", orderDate=" + orderDate
		+ ", lastUpdated=" + lastUpdated + ", updatedBy=" + updatedBy + ", deviceID=" + deviceID + ", updatedDateStr="
		+ updatedDateStr + "]";
    }

    private String toString(Collection<?> collection, int maxLen) {
	StringBuilder builder = new StringBuilder();
	builder.append("[");
	int i = 0;
	for (Iterator<?> iterator = collection.iterator(); iterator.hasNext() && i < maxLen; i++) {
	    if (i > 0)
		builder.append(", ");
	    builder.append(iterator.next());
	}
	builder.append("]");
	return builder.toString();
    }

    public String getOrderDisplay() {
	orderDisplay = Util.orderDisplay(this.orderID);
	return orderDisplay;
    }

    public void setOrderDisplay(String orderDisplay) {
	this.orderDisplay = orderDisplay;
    }
}
